image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - npm install
    - npm install -g @angular/cli
    - npm install -g firebase-tools
    - ng build --prod --outputHashing=all
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
